# Site settings
title: Emile Cantin's Blog
email: emile.cantin@gmail.com
description: >
  My name is Emile Cantin, dad of 4 girls, amateur sailor, and all-around geek.
  I mostly blog about some interesting problems I encounter in my day-to-day
  life as a software developer. I'm currently employed at tyl.io, where
  I push the envelope on what's possible on the Web.
baseurl: ""
url: "http://blog.emilecantin.com"
twitter_username: emilecantin
github_username:  emilecantin

# Build settings
paginate: 25
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
